//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace consoleapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialOrders
    {
        public int OrderID { get; set; }
        public int MaterialID { get; set; }
        public int QuantityOrdered { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int ProjectID { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Projects Projects { get; set; }
    }
}
